### ISSUE TITLE
#allow-insecure-localhost flag has been removed

### ISSUE THREAD

**Issue by htysc** [csse-uoft/SNM-I#97]
https://github.com/csse-uoft/SNM-I/blob/2f9b154a04a6b314f2d5efb0e6654e9c1b70f56c/doc/src/content/docs/project-setup.md?plain=1#L83
This flag has recently been removed. A temporary [fix](https://support.google.com/chrome/thread/241869686/allow-insecure-localhost-has-been-removed-as-of-chrome-119) is enabling "#temporary-unexpire-flags-m118". A lasting fix would be a valid certificate.

**Comment by LesterLyu** [comment]
You will need to trust the certificate if the flag is removed. There is no valid certificate for localhost.
